#! /bin/sh

# Change names of all files in the wd to specific case
# Usage : ChCaseFN <option>
# <option> is `l' || `u' respectively meanning lowercase || uppercase

if [ ! "$#" -eq 1 ]
then
	echo "Usage : $0 <l|u>"
	exit 1
fi

ls | more |
while read file
do
	if [ $file = $0 -o ./$file = $0 ] 
	then
		continue
	fi
	new_file=`ChCase $1 <<- END
		$file
	END`
	mv $file $new_file
done
